site_name: CGH Patient Handbook
theme:
  name: material
  palette:
    scheme: default
    primary: light-blue
    accent: cyan

nav:
  - Emergency:
      - Overview: emergency/index.md
  - Clinical Specialties & Services:
      - Overview: clinical-specialties/index.md
  - Independent Services: independent-services/index.md
  - Nursing: nursing/index.md
  - Pharmacy: pharmacy/index.md
  - Allied Health Departments / Units (ALL): allied-health/index.md
  - Specialist Centres & Clinics (ALL): specialist-centres/index.md
  - Other Services / Programmes: other-services/index.md

